import Head from "next/head";
// import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import AOS from "aos";
import "aos/dist/aos.css";
import React, { useEffect, useRef, useState } from "react";
import Experiance from "./components/Experiance";
import Education from "./components/Education";

// const inter = Inter({ subsets: ["latin"] });
const Os = React.lazy(() => import(/* webpackChunkName: 'os' */ /* webpackPrefetch: true */ "./components/Os"));
const Project = React.lazy(() => import(/* webpackChunkName: 'project' */ /* webpackPrefetch: true */ "./components/Project"));
const Skill = React.lazy(() => import(/* webpackChunkName: 'skill' */ /* webpackPrefetch: true */ "./components/Skill"));
const Footer = React.lazy(() => import(/* webpackChunkName: 'footer' */ /* webpackPrefetch: true */ "./components/Footer"));

export default function Home() {
  const [isLoading, setLoading] = useState(true);

  useEffect(() => {
    AOS.init();
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  }, []);

  const homeRef = useRef();
  const aboutRef = useRef();
  const skillsRef = useRef();
  const experianceRef = useRef();
  const educationRef = useRef();
  const projectRef = useRef();
  const findUsRef = useRef();

  const scrollToRef = (ref) => {
    ref.current.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <title>MrABi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isLoading ? (
        <React.Suspense>
          <main className={styles.main} ref={homeRef}>
            <Os aboutRef={aboutRef} aboutFun={() => scrollToRef(aboutRef)} experianceFun={() => scrollToRef(experianceRef)} educationFun={() => scrollToRef(educationRef)} projectFun={() => scrollToRef(projectRef)} skillsFun={() => scrollToRef(skillsRef)} findUsFun={() => scrollToRef(findUsRef) } />
            <Skill skillsRef={skillsRef} />
            <Experiance experianceRef={experianceRef} />
            <Education educationRef={educationRef} />
            <Project projectRef={projectRef} />
            <Footer findUsRef={findUsRef} />
          </main>
          <div className={styles.custom_position}>
            <button type="button" onClick={() => scrollToRef(homeRef)}>
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 11l7-7 7 7M5 19l7-7 7 7"></path>
              </svg>
              <span>UP</span>
            </button>
          </div>
        </React.Suspense>
      ) : (
        <div className={styles.loader}>
          <div className={styles.spinner}>
            <span className={styles.spinner_part_0}></span>
            <span className={styles.spinner_part_1}></span>
            <span className={styles.spinner_part_2}></span>
            <span className={styles.spinner_part_3}></span>
            <span className={styles.spinner_part_0}></span>
            <span className={styles.spinner_part_1}></span>
            <span className={styles.spinner_part_2}></span>
            <span className={styles.spinner_part_3}></span>
          </div>
        </div>
      )}
    </>
  );
}
